package GUI;
import javax.swing.JOptionPane;
/**
 *
 * @author Li
 */
public class Calculadora extends javax.swing.JFrame {

    private String cadenaNumeros = "", cadenaMemory = "";
    private String operacion = "nula";
    private double primerNumero, resultado, memoryfirst, memoryResult;
    private boolean activado = true;
    private boolean punto = true;
    double segundoNumero, memorySecond;

    public Calculadora() {
        initComponents();
        this.setTitle("Calculadora");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblNumeros = new javax.swing.JLabel();
        lblMuestra = new javax.swing.JLabel();
        btn0 = new javax.swing.JButton();
        btnMC = new javax.swing.JButton();
        btnMR = new javax.swing.JButton();
        btnMS = new javax.swing.JButton();
        btnMMas = new javax.swing.JButton();
        btnMMenos = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnMasMenos = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnPorcentaje = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnMOD = new javax.swing.JButton();
        btnComa = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        lblNumeros.setBackground(new java.awt.Color(153, 153, 153));
        lblNumeros.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblNumeros.setForeground(new java.awt.Color(0, 0, 0));
        lblNumeros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumeros.setText("0");
        lblNumeros.setToolTipText("");
        lblNumeros.setOpaque(true);

        lblMuestra.setBackground(new java.awt.Color(153, 153, 153));
        lblMuestra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMuestra.setForeground(new java.awt.Color(0, 0, 0));
        lblMuestra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMuestra.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(lblMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumeros)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, -1));

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 130, 50));

        btnMC.setText("MC");
        btnMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMCActionPerformed(evt);
            }
        });
        jPanel1.add(btnMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 60, 50));

        btnMR.setText("MR");
        btnMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRActionPerformed(evt);
            }
        });
        jPanel1.add(btnMR, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 60, 50));

        btnMS.setText("MS");
        btnMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMSActionPerformed(evt);
            }
        });
        jPanel1.add(btnMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 60, 50));

        btnMMas.setText("M+");
        btnMMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMMasActionPerformed(evt);
            }
        });
        jPanel1.add(btnMMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 60, 50));

        btnMMenos.setText("M-");
        btnMMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMMenosActionPerformed(evt);
            }
        });
        jPanel1.add(btnMMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 70, 50));

        jButton7.setText("<--");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 60, 50));

        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });
        jPanel1.add(btnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 60, 50));

        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        jPanel1.add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 60, 50));

        btnMasMenos.setText("+/-");
        btnMasMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasMenosActionPerformed(evt);
            }
        });
        jPanel1.add(btnMasMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 60, 50));

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 50));

        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        jPanel1.add(btnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 70, 110));

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 60, 50));

        btnDivision.setText("/");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        jPanel1.add(btnDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 60, 50));

        btnPorcentaje.setText("%");
        btnPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcentajeActionPerformed(evt);
            }
        });
        jPanel1.add(btnPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 70, 50));

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 60, 50));

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 60, 50));

        jButton18.setText("jButton1");
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 90, 50));

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 60, 50));

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 60, 50));

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 60, 50));

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 60, 50));

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 60, 50));

        btnMultiplicacion.setText("*");
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 60, 50));

        btnMOD.setText("MOD");
        btnMOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMODActionPerformed(evt);
            }
        });
        jPanel1.add(btnMOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 70, 50));

        btnComa.setText(",");
        btnComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComaActionPerformed(evt);
            }
        });
        jPanel1.add(btnComa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 60, 50));

        btnResta.setText("-");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        jPanel1.add(btnResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 60, 50));

        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 60, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        
        if (activado == true) {
            primerNumero = Double.parseDouble(cadenaNumeros);
            lblMuestra.setText(cadenaNumeros + " - ");
            cadenaNumeros = "";
            operacion = "restar";

            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
       if(lblNumeros.getText().length() != 10){
        if (lblNumeros.getText().equals("0")) {
            cadenaNumeros = "0";
            cadenaMemory = "0";
        } else {
            cadenaNumeros += "0";
            cadenaMemory += "0";
        }
        lblNumeros.setText(cadenaNumeros);
        activado = true;// Voy a usar la calculadora
       }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
       if(lblNumeros.getText().length() != 10){
        if (lblNumeros.getText().equals("0")) {
            cadenaNumeros = "1";
            cadenaMemory = "1";
        } else {
            cadenaNumeros += "1";
            cadenaMemory += "1";
        }
        lblNumeros.setText(cadenaNumeros);
        activado = true;// Voy a usar la calculadora
       }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (lblNumeros.getText().equals("0")) {
            cadenaNumeros = "2";
            cadenaMemory = "2";
        } else {
            cadenaNumeros += "2";
            cadenaMemory += "2";
        }
        lblNumeros.setText(cadenaNumeros);
        activado = true;// Voy a usar la calculadora
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
       if(lblNumeros.getText().length() != 10){
        if (lblNumeros.getText().equals("0")) {
             cadenaNumeros = "3";
            cadenaMemory = "3";
        } else {
            cadenaNumeros += "3";
            cadenaMemory += "3";
        }
        lblNumeros.setText(cadenaNumeros);
        activado = true;// Voy a usar la calculadora 
       }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
       if(lblNumeros.getText().length() != 10){
           
        if (lblNumeros.getText().equals("0")) {
            cadenaNumeros = "4";
            cadenaMemory = "4";
        } else {
            cadenaNumeros += "4";
            cadenaMemory += "4";
        }
        lblNumeros.setText(cadenaNumeros);
        activado = true;// Voy a usar la calculadora  
       }else{
           JOptionPane.showMessageDialog(null, "Muchos caracteres ");
       }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
       if(lblNumeros.getText().length() != 10){
        if (lblNumeros.getText().equals("0")) {
             cadenaNumeros = "5";
            cadenaMemory = "5";
        } else {
            cadenaNumeros += "5";
            cadenaMemory += "5";
        }
        lblNumeros.setText(cadenaNumeros);
        activado = true;// Voy a usar la calculadora 
       }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
       if(lblNumeros.getText().length() != 10){
        if (lblNumeros.getText().equals("0")) {
             cadenaNumeros = "6";
            cadenaMemory = "6";
        } else {
            cadenaNumeros += "6";
            cadenaMemory += "6";
        }
        lblNumeros.setText(cadenaNumeros);
        activado = true;// Voy a usar la calculadora 
       }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
       if(lblNumeros.getText().length() != 10){
        if (lblNumeros.getText().equals("0")) {
              cadenaNumeros = "7";
            cadenaMemory = "7";
        } else {
            cadenaNumeros += "7";
            cadenaMemory += "7";
        }
        lblNumeros.setText(cadenaNumeros);
        activado = true;// Voy a usar la calculadora
       }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
       if(lblNumeros.getText().length() != 10){
        if (lblNumeros.getText().equals("0")) {
           cadenaNumeros = "8";
            cadenaMemory = "8";
        } else {
            cadenaNumeros += "8";
            cadenaMemory += "8";
        }
        lblNumeros.setText(cadenaNumeros);
        activado = true;// Voy a usar la calculadora
       }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
      if(lblNumeros.getText().length() != 10){
        if (lblNumeros.getText().equals("0")) {
           cadenaNumeros = "9";
            cadenaMemory = "9";
        } else {
            cadenaNumeros += "9";
            cadenaMemory += "9";
        }
        lblNumeros.setText(cadenaNumeros);
        activado = true;// Voy a usar la calculadora 
      }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
       
        if (activado == true) {
            primerNumero = Double.parseDouble(cadenaNumeros);
            lblMuestra.setText(cadenaNumeros + " + ");
            cadenaNumeros = "";
            operacion = "sumar";

            activado = false;
        }
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        if (activado == true) {
            primerNumero = Double.parseDouble(cadenaNumeros);
            lblMuestra.setText(cadenaNumeros + " X ");
            cadenaNumeros = "";
            operacion = "multiplicar";

            activado = false;

        }
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        if (activado == true) {
            primerNumero = Double.parseDouble(cadenaNumeros);
            lblMuestra.setText(cadenaNumeros + " / ");
            cadenaNumeros = "";
            operacion = "dividir";

            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnMasMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasMenosActionPerformed
        if (cadenaNumeros.charAt(0) != '-') {
            cadenaNumeros = "-" + cadenaNumeros;

        } else {
            cadenaNumeros = cadenaNumeros.substring(1, cadenaNumeros.length());
        }
        lblNumeros.setText(cadenaNumeros);
    }//GEN-LAST:event_btnMasMenosActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed

        if (operacion.equals("nula")) {
            lblNumeros.setText(cadenaNumeros);
        } else if (operacion.equals("sumar")) {
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero + segundoNumero;
            lblNumeros.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
        } else if (operacion.equals("restar")) {
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero - segundoNumero;
            lblNumeros.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
        } else if (operacion.equals("multiplicar")) {
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero * segundoNumero;
            lblNumeros.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
            
        } else if (operacion.equals("dividir")) {
            segundoNumero = Double.parseDouble(cadenaNumeros);
            if (segundoNumero == 0) {
                lblNumeros.setText("NoEsDivisiblePor0");
            } else {
                resultado = primerNumero / segundoNumero;
                lblNumeros.setText(String.format("% .2f", resultado));
                cadenaNumeros = String.valueOf(resultado);
                operacion = "nula";
            }
            } else if (operacion.equals("porcentaje")) {
            segundoNumero = Double.parseDouble(cadenaNumeros);
           
                resultado = primerNumero * (segundoNumero/100);
                lblNumeros.setText(String.format("% .2f", resultado));
                cadenaNumeros = String.valueOf(resultado);
                operacion = "nula";
            
        }
        lblMuestra.setText("");
        activado = true;

    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComaActionPerformed
        if (punto == true) {
            if (cadenaNumeros.equals("")) {
                cadenaNumeros = "0.";
            } else {
                cadenaNumeros += ".";
            }

        }
    }//GEN-LAST:event_btnComaActionPerformed

    private void btnMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMCActionPerformed
        cadenaMemory = "";
    }//GEN-LAST:event_btnMCActionPerformed

    private void btnMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRActionPerformed
        lblMuestra.setText(cadenaMemory.toString());
    }//GEN-LAST:event_btnMRActionPerformed

    private void btnMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMSActionPerformed
        lblMuestra.setText(cadenaMemory.toString());
    }//GEN-LAST:event_btnMSActionPerformed

    private void btnMMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMMasActionPerformed
        if (activado == true) {
            
            memoryResult+=Double.parseDouble(cadenaMemory);
            cadenaMemory = String.valueOf(memoryResult);
            lblNumeros.setText("0");
        }   
    }//GEN-LAST:event_btnMMasActionPerformed

    private void btnMMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMMenosActionPerformed
        memoryResult-=Double.parseDouble(cadenaMemory);
            cadenaMemory = String.valueOf(memoryResult);
            lblNumeros.setText("0");
    }//GEN-LAST:event_btnMMenosActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        int tamaño = cadenaNumeros.length();
        if (tamaño > 0) {
            if (tamaño == 1) {
                cadenaNumeros = "1";
            } else {
                cadenaNumeros = cadenaNumeros.substring(0, cadenaNumeros.length() - 1);
            }
            lblNumeros.setText(cadenaNumeros);
        }
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        lblMuestra.setText("");
        lblNumeros.setText("0");
        operacion = "nula";
        cadenaNumeros = "";
        activado = true;
        punto = true;
    }//GEN-LAST:event_btnCActionPerformed

    private void btnMODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMODActionPerformed
          if (activado == true) {
            primerNumero = Double.parseDouble(cadenaNumeros);
            lblMuestra.setText(cadenaNumeros + " / ");
            cadenaNumeros = "";
            operacion = "dividir";

            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_btnMODActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int tamaño = cadenaNumeros.length();
      if(tamaño > 0){
          if(tamaño == 1){
              cadenaNumeros = "1";
          }else{
              cadenaNumeros = cadenaNumeros.substring(0, cadenaNumeros.length() - 1);
          }
          lblNumeros.setText(cadenaNumeros);
      }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcentajeActionPerformed
         if (activado == true) {
            primerNumero = Double.parseDouble(cadenaNumeros);
            lblMuestra.setText(cadenaNumeros + " % ");
            cadenaNumeros = "";
            operacion = "porcentaje";

            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_btnPorcentajeActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnComa;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMC;
    private javax.swing.JButton btnMMas;
    private javax.swing.JButton btnMMenos;
    private javax.swing.JButton btnMOD;
    private javax.swing.JButton btnMR;
    private javax.swing.JButton btnMS;
    private javax.swing.JButton btnMasMenos;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnPorcentaje;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMuestra;
    private javax.swing.JLabel lblNumeros;
    // End of variables declaration//GEN-END:variables
}
